apiVersion: apps/v1
kind: Deployment

metadata:
  name: redis-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: redis
          image: gcr.io/omar-yasser-375922/proj-redis
          ports: 
            - containerPort: 6379
